use std::fmt;

pub enum ActId {
    Act1 = 0,
    Act2 = 1,
    Act3 = 2,
    Act4 = 3,
    Act5 = 4,
    NotInitialized = 0xFF,
}

#[allow(dead_code)]
const ACT1_AREAS: &'static [&'static str] = &[
    "Rogue Encampment",
    "Blood Moor",
    "Cold Plains",
    "Stony Field",
    "Dark Wood",
    "Black Marsh",
    "Tamoe Highland",
    "Den Of Evil",
    "Cave Level 1",
    "Underground Passage Level 1",
    "Hole Level 1",
    "Pit Level 1",
    "Cave Level 2",
    "Underground Passage Level 2",
    "Holy Level 2",
    "Pit Level 2",
    "Burial Grounds",
    "Crypt",
    "Mausoleum",
    "Forgotten Tower",
    "Tower Cellar Level 1",
    "Tower Cellar Level 2",
    "Tower Cellar Level 3",
    "Tower Cellar Level 4",
    "Tower Cellar Level 5",
    "Monastery Gate",
    "Outer Cloister",
    "Barracks",
    "Jail Level 1",
    "Jail Level 2",
    "Jail Level 3",
    "Inner Cloister",
    "Inner Cloister 2",
    "Catacombs Level 1",
    "Catacombs Level 2",
    "Catacombs Level 3",
    "Catacombs Level 4",
    "Tristram",
    "The Secret Cow Level",
];

#[allow(dead_code)]
const ACT2_AREAS: &'static [&'static str] = &[
    "Lut Gholein",
    "Rocky Waste",
    "Dry Hills",
    "Far Oasis",
    "Lost City",
    "Valley Of Snakes",
    "Canyon Of The Magi",
    "Sewers Level 1",
    "Sewers Level 2",
    "Sewers Level 3",
    "Harem Level 1",
    "Harem Level 2",
    "Palace Cellar Level 1",
    "Palace Cellar Level 2",
    "Palace Cellar Level 3",
    "Stony Tomb Level 1",
    "Halls Of The Dead Level 1",
    "Halls Of The Dead Level 2",
    "Claw Viper Temple Level 1",
    "Stony Tomb Level 2",
    "Halls Of The Dead Level 3",
    "Claw Viper Temple Level 2",
    "Maggot Lair Level 1",
    "Maggot Lair Level 2",
    "Maggot Lair Level 3",
    "Ancient Tunnels",
    "Tal Rashas Tomb 1",
    "Tal Rashas Tomb 2",
    "Tal Rashas Tomb 3",
    "Tal Rashas Tomb 4",
    "Tal Rashas Tomb 5",
    "Tal Rashas Tomb 6",
    "Tal Rashas Tomb 7",
    "Tal Rashas Chamber",
    "Arcane Sanctuary",
];

#[allow(dead_code)]
const ACT3_AREAS: &'static [&'static str] = &[
    "Kurast Docks",
    "Spider Forest",
    "Great Marsh",
    "Flayer Jungle",
    "Lower Kurast",
    "Kurast Bazaar",
    "Upper Kurast",
    "Kurast Causeway",
    "Travincal",
    "Archnid Lair",
    "Spider Cavern",
    "Swampy Pit Level 1",
    "Swampy Pit Level 2",
    "Flayer Dungeon Level 1",
    "Flayer Dungeon Level 2",
    "Swampy Pit Level 3",
    "Flayer Dungeon Level 3",
    "Sewers Level 1",
    "Sewers Level 2",
    "Ruined Temple",
    "Disused Fane",
    "Forgotten Reliquary",
    "Forgotten Temple",
    "Ruined Fane",
    "Disused Reliquary",
    "Durance Of Hate Level 1",
    "Durance Of Hate Level 2",
    "Durance Of Hate Level 3",
];

#[allow(dead_code)]
const ACT4_AREAS: &'static [&'static str] = &[
    "The Pandemonium Fortress",
    "Outer Steppes",
    "Plains Of Despair",
    "City Of The Damned",
    "River Of Flame",
    "The Chaos Sanctuary",
];

#[allow(dead_code)]
const ACT5_AREAS: &'static [&'static str] = &[
    "Harrogath",
    "The Bloody Foothills",
    "Frigid Highlands",
    "Arreat Plateau",
    "Crystalline Passage",
    "Frozen River",
    "Glacial Trail",
    "Drifter Cavern",
    "Frozen Tundra",
    "The Ancients Way",
    "Icy Cellar",
    "Arreat Summit",
    "Nihlathaks Temple",
    "Halls Of Anguish",
    "Halls Of Pain",
    "Halls Of Vaught",
    "Abaddon",
    "Pit Of Acheron",
    "Infernal Pit",
    "Worldstone Keep Level 1",
    "Worldstone Keep Level 2",
    "Worldstone Keep Level 3",
    "Throne Of Destruction",
    "Worldstone Keep",
    "Matrons Den",
    "Forgotten Sands",
    "Furnace Of Pain",
    "Uber Tristram",
];


#[repr(u16)]
pub enum Area {
    Unknown             = 0,
    RogueEncampment     = 1,
    BloodMoor           = 2,
    ColdPlains          = 3,
    StonyField          = 4,
    DarkWood            = 5,
    BlackMarsh          = 6,
    TamoeHighland       = 7,
    DenOfEvil           = 8,
    CaveLevel1          = 9,
    UndergroundPassageLevel1 = 10,
    HoleLevel1          = 11,
    PitLevel1           = 12,
    CaveLevel2          = 13,
    UndergroundPassageLevel2 = 14,
    HoleLevel2          = 15,
    PitLevel2           = 16,
    BurialGrounds       = 17,
    Crypt               = 18,
    Mausoleum           = 19,
    ForgottenTower      = 20,
    TowerCellarLevel1   = 21,
    TowerCellarLevel2   = 22,
    TowerCellarLevel3   = 23,
    TowerCellarLevel4   = 24,
    TowerCellarLevel5   = 25,
    MonasteryGate       = 26,
    OuterCloister       = 27,
    Barracks            = 28,
    JailLevel1          = 29,
    JailLevel2          = 30,
    JailLevel3          = 31,
    InnerCloister       = 32,
    Cathedral           = 33,
    CatacombsLevel1     = 34,
    CatacombsLevel2     = 35,
    CatacombsLevel3     = 36,
    CatacombsLevel4     = 37,
    Tristram            = 38,
    MooMooFarm          = 39,
    LutGholein          = 40,
    RockyWaste          = 41,
    DryHills            = 42,
    FarOasis            = 43,
    LostCity            = 44,
    ValleyOfSnakes      = 45,
    CanyonOfTheMagi     = 46,
    SewersLevel1        = 47,
    SewersLevel2        = 48,
    SewersLevel3        = 49,
    HaremLevel1         = 50,
    HaremLevel2         = 51,
    PalaceCellarLevel1  = 52,
    PalaceCellarLevel2  = 53,
    PalaceCellarLevel3  = 54,
    StonyTombLevel1     = 55,
    HallsOfTheDeadLevel1 = 56,
    HallsOfTheDeadLevel2 = 57,
    ClawViperTempleLevel1 = 58,
    StonyTombLevel2       = 59,
    HallsOfTheDeadLevel3  = 60,
    ClawViperTempleLevel2 = 61,
    MaggotLairLevel1    = 62,
    MaggotLairLevel2    = 63,
    MaggotLairLevel3    = 64,
    AncientTunnels      = 65,
    TalRashasTomb1      = 66,
    TalRashasTomb2      = 67,
    TalRashasTomb3      = 68,
    TalRashasTomb4      = 69,
    TalRashasTomb5      = 70,
    TalRashasTomb6      = 71,
    TalRashasTomb7      = 72,
    TalRashasChamber    = 73,
    ArcaneSanctuary     = 74,
    KurastDocks         = 75,
    SpiderForest        = 76,
    GreatMarsh          = 77,
    FlayerJungle        = 78,
    LowerKurast         = 79,
    KurastBazaar        = 80,
    UpperKurast         = 81,
    KurastCauseway      = 82,
    Travincal           = 83,
    SpiderCave          = 84,
    SpiderCavern        = 85,
    SwampyPitLevel1     = 86,
    SwampyPitLevel2     = 87,
    FlayerDungeonLevel1 = 88,
    FlayerDungeonLevel2 = 89,
    SwampyPitLevel3     = 90,
    FlayerDungeonLevel3 = 91,
    KurastSewersLevel1  = 92,
    KurastSewersLevel2  = 93,
    RuinedTemple        = 94,
    DisusedFane         = 95,
    ForgottenReliquary  = 96,
    ForgottenTemple     = 97,
    RuinedFane          = 98,
    DisusedReliquary    = 99,
    DuranceOfHateLevel1 = 100,
    DuranceOfHateLevel2 = 101,
    DuranceOfHateLevel3 = 102,
    ThePandemoniumFortress = 103,
    OuterSteppes        = 104,
    PlainsOfDespair     = 105,
    CityOfTheDamned     = 106,
    RiverOfFlame        = 107,
    TheChaosSanctuary   = 108,
    Harrogath           = 109,
    BloodyFoothills     = 110,
    FrigidHighlands     = 111,
    ArreatPlateau       = 112,
    CrystallinePassage  = 113,
    FrozenRiver         = 114,
    GlacialTrail        = 115,
    DrifterCavern       = 116,
    FrozenTundra        = 117,
    TheAncientsWay      = 118,
    IcyCellar           = 119,
    ArreatSummit        = 120,
    NihlathaksTemple    = 121,
    HallsOfAnguish      = 122,
    HallsOfPain         = 123,
    HallsOfVaught       = 124,
    Abaddon             = 125,
    PitOfAcheron        = 126,
    InfernalPit         = 127,
    TheWorldstoneKeepLevel1 = 128,
    TheWorldstoneKeepLevel2 = 129,
    TheWorldstoneKeepLevel3 = 130,
    ThroneOfDestruction     = 131,
    TheWorldstoneChamber    = 132,
    MatronsDen              = 133,
    ForgottenSands          = 134,
    FurnaceOfPain           = 135,
    UberTristram            = 136
}


impl std::fmt::Display for Area {
    fn fmt(&self, formatter: &mut fmt::Formatter) -> fmt::Result {
        use Area::*;
        let s = match *self {
            Unknown =>          "Unknown",
            RogueEncampment =>  "Rogue Encampment",
            BloodMoor =>        "Blood Moor",
            ColdPlains =>       "Cold Plains",
            StonyField =>       "Stony Field",
            DarkWood =>         "Dark Wood",
            BlackMarsh =>       "Black Marsh",
            TamoeHighland =>    "Tamoe Highland",
            DenOfEvil =>        "Den Of Evil",
            CaveLevel1 =>       "Cave Level 1",
            UndergroundPassageLevel1 => "Underground Passage Level 1",
            HoleLevel1 =>               "Hole Level 1",
            PitLevel1 =>                "Pit Level 1",
            CaveLevel2 =>               "Cave Level 2",
            UndergroundPassageLevel2 => "Underground Passage Level 2",
            HoleLevel2 =>           "Hole Level 2",
            PitLevel2 =>            "Pit Level 2",
            BurialGrounds =>        "Burial Grounds",
            Crypt =>                "Crypt",
            Mausoleum =>            "Mausoleum",
            ForgottenTower =>       "Forgotten Tower",
            TowerCellarLevel1 =>    "Tower Cellar Level 1",
            TowerCellarLevel2 =>    "Tower Cellar Level 2",
            TowerCellarLevel3 =>    "Tower Cellar Level 3",
            TowerCellarLevel4 =>    "Tower Cellar Level 4",
            TowerCellarLevel5 =>    "Tower Cellar Level 5",
            MonasteryGate =>        "Monastery Gate",
            OuterCloister =>        "Outer Cloister",
            Barracks =>             "Barracks",
            JailLevel1 =>           "Jail Level 1",
            JailLevel2 =>           "Jail Level 2",
            JailLevel3 =>           "Jail Level 3",
            InnerCloister =>        "Inner Cloister",
            Cathedral =>            "Cathedral",
            CatacombsLevel1 =>      "Catacombs Level 1",
            CatacombsLevel2 =>      "Catacombs Level 2",
            CatacombsLevel3 =>      "Catacombs Level 3",
            CatacombsLevel4 =>      "Catacombs Level 4",
            Tristram =>             "Tristram",
            MooMooFarm =>           "Moo Moo Farm",
            LutGholein =>           "Lut Gholein",
            RockyWaste =>           "Rocky Waste",
            DryHills =>             "Dry Hills",
            FarOasis =>             "Far Oasis",
            LostCity =>             "Lost City",
            ValleyOfSnakes =>       "Valley Of Snakes",
            CanyonOfTheMagi =>      "Canyon Of The Magi",
            SewersLevel1 =>         "Sewers Level 1",
            SewersLevel2 =>         "Sewers Level 2",
            SewersLevel3 =>         "Sewers Level 3",
            HaremLevel1=>           "Harem Level 1",
            HaremLevel2 =>          "Harem Level 2",
            PalaceCellarLevel1 =>   "Palace Cellar Level 1",
            PalaceCellarLevel2 =>   "Palace Cellar Level 2",
            PalaceCellarLevel3 =>   "Palace Cellar Level 3",
            StonyTombLevel1 =>          "Stony Tomb Level 1",
            HallsOfTheDeadLevel1 =>     "Halls Of The Dead Level 1",
            HallsOfTheDeadLevel2 =>     "Halls Of The Dead Level 2",
            ClawViperTempleLevel1 =>    "Claw Viper Temple Level 1",
            StonyTombLevel2 =>          "Stony Tomb Level 2",
            HallsOfTheDeadLevel3 =>     "Halls Of The Dead Level 3",
            ClawViperTempleLevel2 =>    "Claw Viper Temple Level 2",
            MaggotLairLevel1 =>         "Maggot Lair Level 1",
            MaggotLairLevel2 =>         "Maggot Lair Level 2",
            MaggotLairLevel3 =>         "Maggot Lair Level 3",
            AncientTunnels =>           "Ancient Tunnels",
            TalRashasTomb1 =>           "Tal Rashas Tomb 1",
            TalRashasTomb2 =>           "Tal Rashas Tomb 2",
            TalRashasTomb3 =>           "Tal Rashas Tomb 3",
            TalRashasTomb4 =>           "Tal Rashas Tomb 4",
            TalRashasTomb5 =>           "Tal Rashas Tomb 5",
            TalRashasTomb6 =>           "Tal Rashas Tomb 6",
            TalRashasTomb7 =>           "Tal Rashas Tomb 7",
            TalRashasChamber =>         "Tal Rashas Chamber",
            ArcaneSanctuary =>          "Arcane Sanctuary",
            KurastDocks =>              "Kurast Docks",
            SpiderForest =>             "Spider Forest",
            GreatMarsh =>               "Great Marsh",
            FlayerJungle =>             "Flayer Jungle",
            LowerKurast =>              "Lower Kurast",
            KurastBazaar =>             "Kurast Bazaar",
            UpperKurast =>              "Upper Kurast",
            KurastCauseway =>           "Kurast Causeway",
            Travincal =>                "Travincal",
            SpiderCave =>               "Spider Cave",
            SpiderCavern =>             "Spider Cavern",
            SwampyPitLevel1 =>          "Swampy Pit Level 1",
            SwampyPitLevel2 =>          "Swampy Pit Level 2",
            FlayerDungeonLevel1 =>      "Flayer Dungeon Level 1",
            FlayerDungeonLevel2 =>      "Flayer Dungeon Level 2",
            SwampyPitLevel3 =>          "Swampy Pit Level 3",
            FlayerDungeonLevel3 =>      "Flayer Dungeon Level 3",
            KurastSewersLevel1 =>       "Kurast Sewers Level 1",
            KurastSewersLevel2 =>       "Kurast Sewers Level 2",
            RuinedTemple =>             "Ruined Temple",
            DisusedFane =>              "Disused Fane",
            ForgottenReliquary =>       "Forgotten Reliquary",
            ForgottenTemple =>          "Forgotten Temple",
            RuinedFane =>               "Ruined Fane",
            DisusedReliquary =>         "Disused Reliquary",
            DuranceOfHateLevel1 =>      "Durance Of Hate Level 1",
            DuranceOfHateLevel2 =>      "Durance Of Hate Level 2",
            DuranceOfHateLevel3 =>      "Durance Of Hate Level 3",
            ThePandemoniumFortress =>   "The Pandemonium Fortress",
            OuterSteppes =>             "Outer Steppes",
            PlainsOfDespair =>          "Plains Of Despair",
            CityOfTheDamned =>          "City Of The Damned",
            RiverOfFlame =>             "River Of Flame",
            TheChaosSanctuary =>        "The Chaos Sanctuary",
            Harrogath =>                "Harrogath",
            BloodyFoothills =>          "Bloody Foothills",
            FrigidHighlands =>          "Frigid Highlands",
            ArreatPlateau =>            "Arreat Plateau",
            CrystallinePassage =>       "Crystalline Passage",
            FrozenRiver =>              "Frozen River",
            GlacialTrail =>             "Glacial Trail",
            DrifterCavern =>            "Drifter Cavern",
            FrozenTundra =>             "Frozen Tundra",
            TheAncientsWay =>           "The Ancients Way",
            IcyCellar =>                "Icy Cellar",
            ArreatSummit =>             "Arreat Summit",
            NihlathaksTemple =>         "Nihlathaks Temple",
            HallsOfAnguish =>           "Halls Of Anguish",
            HallsOfPain =>              "Halls Of Pain",
            HallsOfVaught =>            "Halls Of Vaught",
            Abaddon =>                  "Abaddon",
            PitOfAcheron =>             "Pit Of Acheron",
            InfernalPit =>              "Infernal Pit",
            TheWorldstoneKeepLevel1 =>  "The Worldstone Keep Level 1",
            TheWorldstoneKeepLevel2 =>  "The Worldstone Keep Level 2",
            TheWorldstoneKeepLevel3 =>  "The Worldstone Keep Level 3",
            ThroneOfDestruction =>      "Throne Of Destruction",
            TheWorldstoneChamber =>     "The Worldstone Chamber",
            MatronsDen =>               "Matrons Den",
            ForgottenSands =>           "Forgotten Sands",
            FurnaceOfPain =>            "Furnace Of Pain",
            UberTristram =>             "Uber Tristram"
        };
        write!(formatter, "{}", s)
    }
}
